### ISSUE TITLE
detection alerts in the portal don't always show in the detection tab

### ISSUE THREAD

**Issue by 1guardianofthegalaxy** [CrowdStrike/falcon-orchestrator#11]
Several alerts today are showing the CS portal but not in the detection tab on Orchestrator.

**Comment by mr-burnse** [comment]
Try clicking the refresh icon in the top left of the navigation bar in Orchestrator.  If you're still not seeing them show up, take a look at the logs to see if there's an issue with the client service.  Troubleshooting steps provided here https://github.com/CrowdStrike/falcon-orchestrator/wiki/Installation-&-Deployment#troubleshooting-the-service.

**Comment by mr-burnse** [comment]
@1guardianofthegalaxy did you get this resolved?

**Comment by mr-burnse** [comment]
Closing due to lack of response, please re-open if still encountering this issue.
