### ISSUE TITLE
Username/Password prompt on first login

### ISSUE THREAD

**Issue by droptables** [CrowdStrike/falcon-orchestrator#23]
I got the MSQL DB up and communicating with the web app.  On first visit to http://localhost, I am prompted for username/password but am unclear on what I need to give it.

I tried the accounts i put in 'allowed users' but those didn't work. Am I missing something?

Thanks!

<img width="1436" alt="screen shot 2017-01-31 at 2 57 48 pm" src="https://cloud.githubusercontent.com/assets/5084547/22489128/887412f6-e7ca-11e6-8c73-b5e8446929b7.png">

**Comment by mr-burnse** [comment]
Yes that's correct, the "allowed users" defined the Windows accounts which have access to login to the web application.  If you're running the server as a standalone/workgroup setup, this should be a local windows account. If attached to a domain you can use domain accounts.

Try the following to troubleshoot:

Open the `C:\inetpub\Falcon Orchestrator\web.config` file and verify the account(s) added within the section ` <authentication mode="Windows"/>
      <sessionState timeout="120"/>
    <authorization>
      <allow users="hostname\username"/>
      <deny users="*"/>
    </authorization>`. Make sure this is setup as expected. NOTE the format should follow hostname\username (use the actual hostname not localhost) for local accounts and domain\username for domain accounts.

**Comment by droptables** [comment]
Ah gotcha. That worked. Thanks!
