### ISSUE TITLE
email alert delivery time does not match start time of detections

### ISSUE THREAD

**Issue by copos45** [CrowdStrike/falcon-orchestrator#40]
Orchestrator has been configured to send email notifications but it has been noticed that the emails being sent are often 20min to several hours after the malware detection.  The Orchestrator console on the other hand, does match up within a few minutes with the Crowdstrike Falcon Cloud console.  

Is there a setting that can be specified to hard-code a window within which email alerts must be sent upon malware detection?  And one for the Orchestrator console itself to retrieve data using the Streaming API?

thanks,
Chris

**Comment by mr-burnse** [comment]
It's difficult to determine what the cause of this might be without being able to troubleshoot in your environment specifically. No there's no way to configure this...if email alerting is configured, the client service should be sending an email notification when it processes each even from the streaming API.

**Comment by copos45** [comment]
**please note my email address change**
Alright I understand there may be something specific to my environment but I’ve checked the time sync settings on the Orchestrator Windows server instance and it is being controlled through Windows Group Policy as designed.  I want to stress that the email alerts do function except some arrive within 15min of the malware detection, whereas others take several hours with no clear pattern between the two.

Considering no one seems to be experiencing the same problem, I do not expect a new release/bug fix to be issued.  But what is the date for the next release and is there a list of the bugs to be corrected in that release, available?
Thanks,
Christopher Chan

**Comment by mr-burnse** [comment]
Can you possible check your email server logs to see if they're queuing up there? That would help to isolate where the issue lies. There's no targeted date for the next release at this time. Although i'm hoping to have something within the next couple months. Bug fixes to be addressed are currently filed as issues with a tag of "bug".

**Comment by copos45** [comment]
**please note my email address change**
I’ve made that request to the Exchange admin but I’m starting to believe Orchestrator is not the factor here.  Some tests will be run in the meantime, thanks.

**Comment by copos45** [comment]
**please note my email address change**
Hi Chris,
Was it possible to see at what time Orchestrator received an alert from the Crowdsrike cloud, and then see at what time Orchestrator attempted to contact the Exchange mail server to forward the alert as an email message?

Performing a Wireshark trace on the Orchestrator host while generating a single Crowdstrike alert on your Office PC should allow Crowdstrike support to answer those questions, and that would pinpoint where the delay is.

Robert

From: Chan, Christopher <CChan@fisa-opa.nyc.gov<mailto:CChan@fisa-opa.nyc.gov>>
Date: Friday, Jun 30, 2017, 1:37 PM
To: CrowdStrike/falcon-orchestrator <reply@reply.github.com<mailto:reply@reply.github.com>>, CrowdStrike/falcon-orchestrator <falcon-orchestrator@noreply.github.com<mailto:falcon-orchestrator@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>, Tortorelli, Robert <RTortorelli@fisa-opa.nyc.gov<mailto:RTortorelli@fisa-opa.nyc.gov>>, Kabir, Shamim <SKabir@fisa-opa.nyc.gov<mailto:SKabir@fisa-opa.nyc.gov>>
Subject: RE: [CrowdStrike/falcon-orchestrator] email alert delivery time does not match start time of detections (#40)

I’ve made that request to the Exchange admin but I’m starting to believe Orchestrator is not the factor here.  Some tests will be run in the meantime, thanks.

**Comment by mr-burnse** [comment]
If you turn the client logging on in debug mode you should get timestamps of when the email is sent....https://github.com/CrowdStrike/falcon-orchestrator/wiki/Installation-&-Deployment#troubleshooting-the-service

**Comment by copos45** [comment]
**please note my email address change**
Yes, as part of my earlier troubles with Orchestrator I did enable “debug” mode as the site recommends.  It seems both Crowdstrike Cloud console and Orchestrator are both registering events within seconds of each other during a test event and earlier detections.  I’m inclined to assume Orchestrator is not at fault here (I’ll note that on the github site) but a third-party mechanism that is out of my control.

Thanks,
Christopher Chan

**Comment by copos45** [comment]
Upon advice of email team, using their smtp-relay.  Orchestrator is likely not a cause in late alert delivery.
