### ISSUE TITLE
Issue connecting to the database

### ISSUE THREAD

**Issue by dlkeeling** [CrowdStrike/falcon-orchestrator#42]
I am getting the following when connecting to the web page. the database is on a SQL server not local.

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

**Comment by dlkeeling** [comment]
Is there an example of what the Web.config file should look like when using a remote database?

**Comment by mr-burnse** [comment]
Please check out issue #31 as this is related. The web.config file should point the database connection string to the IP or Hostname of your db server followed by \Instance_name of a SQL instance is being used.

**Comment by dlkeeling** [comment]
Thanks that fixed it.
