### ISSUE TITLE
Malformed audit event timestamp, failing over to current time

### ISSUE THREAD

**Issue by doncountduckula** [CrowdStrike/falcon-orchestrator#47]
Hi there - I'm seeing this event every couple minutes in the 'runlog' - I'm receiving detection events but not sure if this is a problem. 

'2018-02-21 14:52:45,948 WARN  FalconOrchestrator.Client.AuditEvent - Malformed audit event timestamp, failing over to current time'

Thanks so much in advance.

**Comment by mr-burnse** [comment]
Hey @doncountduckula, This is expected and can be safely ignored. I would also suggest setting the log configuration to ERROR for normal operation. That way these messages wont grow the log file over time.
