### ISSUE TITLE
Email notifications do not show detection 'End Time'

### ISSUE THREAD

**Issue by doncountduckula** [CrowdStrike/falcon-orchestrator#49]
Email notifications for detections are coming through just fine, however for process endtime within the email notification we're getting the following:

End Time | {{ProcessEndtime}}

So instead of seeing the actual processendtime we see the placeholder for it.
The detection appears fine on the Orchestrator web ui.

Thanks!
-lucas

**Comment by mr-burnse** [comment]
Closing due to inactivty, please re-open if this hasn't fixed the issue.
