### ISSUE TITLE
  Error! Exception calling "GetOwner" : "Not found " 

### ISSUE THREAD

**Issue by dlkeeling** [CrowdStrike/falcon-orchestrator#51]
Getting this error when doing a computer search in "Process Listing".

Search works file for File Extraction, File System Browser & Software Inventory. 

Any help would be appreciated.

**Comment by mr-burnse** [comment]
@dlkeeling Apologies for the delayed response.  Can you please try running the PS script directly and let me know what results you get ? The script is located @ https://github.com/CrowdStrike/falcon-orchestrator/blob/master/FalconOrchestrator.Web/App_Data/Scripts/Get-ProcessListing.ps1
