### ISSUE TITLE
Configuring CS-Orchestrator Alerts

### ISSUE THREAD

**Issue by thapdhe** [CrowdStrike/falcon-orchestrator#53]
How to configure the CS- Orchestrator to send alert and fetch the data from Cloud host to Orchestrator, and set the email alerts to team

**Comment by mr-burnse** [comment]
Please take a look at the https://github.com/CrowdStrike/falcon-orchestrator/wiki/Installation-&-Deployment#email section of the documents which outlines some of the configuration required for this. Let me know if you run into any issues!

**Comment by thapdhe** [comment]
The installation is completed. And email alerts working fine now. Now exploring the features.

Thanks for your help.
