### ISSUE TITLE
Ticketing Stack Trace Issue

### ISSUE THREAD

**Issue by esquared617** [CrowdStrike/falcon-orchestrator#7]
When I select Ticketing, I get the following stack trace:

Server Error in '/' Application.

TryExpression is not supported as a child expression when accessing a member on type 'System.Nullable`1[System.DateTime]' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.NotSupportedException: TryExpression is not supported as a child expression when accessing a member on type 'System.Nullable`1[System.DateTime]' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[NotSupportedException: TryExpression is not supported as a child expression when accessing a member on type 'System.Nullable`1[System.DateTime]' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.]
   System.Linq.Expressions.Compiler.StackSpiller.RequireNotRefInstance(Expression instance) +2253505
   System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack) +4379405
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +114
   System.Linq.Expressions.Compiler.ChildRewriter.Add(Expression node) +37
   System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberAssignment(BinaryExpression node, Stack stack) +122
   System.Linq.Expressions.Compiler.StackSpiller.RewriteAssignBinaryExpression(Expression expr, Stack stack) +4427678
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +408
   System.Linq.Expressions.Compiler.StackSpiller.RewriteBlockExpression(Expression expr, Stack stack) +114
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +294
   System.Linq.Expressions.Compiler.StackSpiller.RewriteTryExpression(Expression expr, Stack stack) +89
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +4379415
   System.Linq.Expressions.Compiler.StackSpiller.RewriteBlockExpression(Expression expr, Stack stack) +114
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +294
   System.Linq.Expressions.Compiler.StackSpiller.RewriteConditionalExpression(Expression expr, Stack stack) +122
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +218
   System.Linq.Expressions.Compiler.StackSpiller.RewriteBlockExpression(Expression expr, Stack stack) +114
   System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack) +294
   System.Linq.Expressions.Compiler.StackSpiller.Rewrite(Expression`1 lambda) +61
   System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller) +44
   System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator) +116
   System.Linq.Expressions.LambdaExpression.Compile() +11
   AutoMapper.MapperFuncs..ctor(MapRequest mapRequest, LambdaExpression typedExpression) +145
   AutoMapper.MapperFuncs..ctor(MapRequest mapRequest, TypeMap typeMap) +132
   AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest) +251
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +132
   AutoMapper.MapperConfiguration.GetMapperFunc(MapRequest mapRequest) +98
   AutoMapper.MapperConfiguration.GetMapperFunc(TypePair types) +240
   AutoMapper.Mapper.AutoMapper.IMapper.Map(TSource source) +314
   FalconOrchestratorWeb.Repository.TicketingRepository.GetList() in C:\Users\eerickson\Downloads\falcon-orchestrator-1.0.0\falcon-orchestrator-1.0.0\FalconOrchestrator.Web\Repository\TicketingRepository.cs:72
   lambda_method(Closure , ControllerBase , Object[] ) +66
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +49
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +49
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +44
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +55
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +45
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +45
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9744261
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1069.1

**Comment by mr-burnse** [comment]
I have not been able to reproduce. Do you currently have any tickets created or is this the first time attempting to navigate to the tickets view?  Also did you install via the provided MSI package or your own build...I see a reference to `C:\Users\eerickson\Downloads\falcon-orchestrator-1.0.0\falcon-orchestrator-1.0.0\FalconOrchestrator.Web\Repository\TicketingRepository.cs:7` which leads me to believe you compiled yourself?

**Comment by esquared617** [comment]
Evan,
It is basically the first time navigating to the tickets.  Don't know if it is relevant, but clicking on Indicators returns an (400) Bad Request. 
I did recompile the msi because it failed repeatedly to create the database so I modified that portion to "Continue on Error =yes" in the database.wxs and manually created the database and tables using the scripts. I did verify the requirements (roles, etc) and matched the OS (2012 R2) and SQL version (2014) to what you specified in the Install documentation. 
Outside of that, the only differences in the recompile would be the versions of MVC and .Net components (Razor, Web.Infrastructure, etc) Shown below.
To be completely honest, I am NOT a developer so it is completely possible and probably likely I have messed this up severly in the recompile; however, it seems only the two functions listed are not working so its almost functional. 
From a holistic perspective, not sure why I couldn't get the database installation to work. Tried using my account which has DA rights and a local account with admin rights on the server.  Doing a SQL trace during install never showed anything touching the SQL server.  Which led to modifying the MSI as described above. 
By the way, I think Brent has setup a call on Thursday with you around this.  I don't want to waste a bunch of your time but we have a small Infosec team and the Orchestrator functionality will be very helpful to them on a daily basis otherwise I would have given up a long time ago.  ;-)
Regards,Eric 

    On Tuesday, July 26, 2016 10:23 AM, Evan Burns <notifications@github.com> wrote:
 

 I have not been able to reproduce. Do you currently have any tickets created or is this the first time attempting to navigate to the tickets view? Also did you install via the provided MSI package or your own build...I see a reference to C:\Users\eerickson\Downloads\falcon-orchestrator-1.0.0\falcon-orchestrator-1.0.0\FalconOrchestrator.Web\Repository\TicketingRepository.cs:7 which leads me to believe you compiled yourself?—

**Comment by mr-burnse** [comment]
Hey Eric, glad the project can be useful to your team! I'm happy to help you get it deployed.  I recently came across this and still need to update the documentation...when installing you need to use a local sql account and not a windows account otherwise the install won't complete properly. This is likely the cause of your installation issues with the MSI.  For installation purposes you can use the sql SA account and change it afterwards or just create a new account within SSMS with adequate permissions.

On our call Thursday, I suggest we walk through re-installing with this in mind.  I suspect this will resolve the issue you're seeing within the ticketing module.  I'm going to close this ticket and we can troubleshoot further Thursday. Cheers!

**Comment by esquared617** [comment]
Evan,
I was able to successfully install Orchestrator on a new production box using the information you provided.  Thank you very much.  The only issue I have (outside of the known 400 error in Indications) is getting the dashboard and Detections to populate.  I have double verified I save both API keys but won't seem to pull data. 
If I can get this resolved, I would say there is no need for the call scheduled tomorrow.  ;-)
Eric 

    On Tuesday, July 26, 2016 12:20 PM, Evan Burns <notifications@github.com> wrote:
 

 Hey Eric, glad the project can be useful to your team! I'm happy to help you get it deployed. I recently came across this and still need to update the documentation...when installing you need to use a local sql account and not a windows account otherwise the install won't complete properly. This is likely the cause of your installation issues with the MSI.  For installation purposes you can use the sql SA account and change it afterwards or just create a new account within SSMS with adequate permissions.On our call Thursday, I suggest we walk through re-installing with this in mind. I suspect this will resolve the issue you're seeing within the ticketing module. I'm going to close this ticket and we can troubleshoot further Thursday. Cheers!—

**Comment by mr-burnse** [comment]
Eric, have you started the Falcon Orchestrator Windows service (https://github.com/CrowdStrike/falcon-orchestrator/wiki/Installation-&-Deployment#starting-the-service)?  If so, are you seeing any errors in the RunLog?  There's a section right underneath in the Wiki which provides some basic troubleshooting.  Please start the service and send any errors you're seeing.  Also to see new detections coming into Orchestrator, make sure you use the refresh button on the top right in the navigation bar.

**Comment by esquared617** [comment]
Per our conversation, generating a new API key seems to be the resolution.  Thanks again for your time and efforts.
